// stdlib
#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
// system
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>


#define PORT 3490
#define BACKLOG 10
// #define k_max_msg 4096
const size_t k_max_msg = 32 << 20;
const size_t k_max_args = 200 * 1000;

// -------------------------------------------------------------------------------------
// HELPERS -----------------------------------------------------------------------------

static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
    fprintf(stderr, "[%d] %s\n", errno, msg);
    abort();
}

static void fd_set_nb(int fd) {
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    (void)fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error");
    }
}

// -------------------------------------------------------------------------------------
// VECTOR ------------------------------------------------------------------------------

// a growable byte buffer, replaces std::vector<uint8_t>
typedef struct {
    uint8_t *buffer_begin;
    uint8_t *buffer_end;
    uint8_t *data_begin;
    uint8_t *data_end;
} Buffer;

static void buf_init(Buffer *buf) {
    buf->buffer_begin = NULL;
    buf->buffer_end = NULL;
    buf->data_begin = NULL;
    buf->data_end = NULL;
}

static void buf_free(Buffer *buf) {
    free(buf->buffer_begin);
    buf->buffer_begin = NULL;
    buf->buffer_end = NULL;
    buf->data_begin = NULL;
    buf->data_end = NULL;
}

static size_t buf_len(const Buffer *buf) {
    return (size_t)(buf->data_end - buf->data_begin);
}

static size_t buf_cap(const Buffer *buf) {
    return (size_t)(buf->buffer_end - buf->buffer_begin);
}

// remove from the front: just advance a pointer, no data movement
static void buf_consume(Buffer *buf, size_t n) {
    assert(n <= buf_len(buf));
    buf->data_begin += n;
    if (buf->data_begin == buf->data_end) {
        // fully drained: reset to the start so future appends get max space
        buf->data_begin = buf->buffer_begin;
        buf->data_end = buf->buffer_begin;
    }
}

// append to the back
static void buf_append(Buffer *buf, const uint8_t *data, size_t len) {
    size_t used = buf_len(buf);
    size_t tail_space = (size_t)(buf->buffer_end - buf->data_end);

    if (tail_space < len) {
        size_t front_space = (size_t)(buf->data_begin - buf->buffer_begin);
        if (front_space + tail_space >= len) {
            // enough total free space: just slide existing data to the front
            memmove(buf->buffer_begin, buf->data_begin, used);
        } else {
            // not enough room even after compacting: grow the allocation
            size_t new_cap = buf_cap(buf) ? buf_cap(buf) * 2 : 64;
            while (new_cap < used + len) {
                new_cap *= 2;
            }
            uint8_t *new_buf = (uint8_t *)malloc(new_cap);
            if (!new_buf) {
                die("malloc error");
            }
            memcpy(new_buf, buf->data_begin, used);  // compact while copying
            free(buf->buffer_begin);
            buf->buffer_begin = new_buf;
            buf->buffer_end = new_buf + new_cap;
        }
        buf->data_begin = buf->buffer_begin;
        buf->data_end = buf->buffer_begin + used;
    }

    memcpy(buf->data_end, data, len);
    buf->data_end += len;
}

// -------------------------------------------------------------------------------------
// CONN --------------------------------------------------------------------------------

typedef struct Conn {
    int fd;
    // application's intention, for the event loop
    bool want_read;
    bool want_write;
    bool want_close;
    // buffered input and output
    Buffer incoming;  // data to be parsed by the application
    Buffer outgoing;  // responses generated by the application
} Conn;

// application callback when the listening socket is ready
static Conn *handle_accept(int fd) {
    // accept
    struct sockaddr_in client_addr = {0};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0) {
        msg_errno("accept() error");
        return NULL;
    }
    uint32_t ip = client_addr.sin_addr.s_addr;
    fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",
        ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
        ntohs(client_addr.sin_port)
    );

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    // create a `struct Conn`
    Conn *conn = (Conn *)malloc(sizeof(Conn));
    memset(conn, 0, sizeof(Conn));
    conn->fd = connfd;
    conn->want_read = true;
    buf_init(&conn->incoming);
    buf_init(&conn->outgoing);
    return conn;
}

// -------------------------------------------------------------------------------------
// STR ---------------------------------------------------------------------------------

// a non-owning view into someone else's bytes (replaces std::string in cmd parsing)
typedef struct Str {
    const uint8_t *data;
    size_t len;
} Str;

// growable array of Str, replaces std::vector<std::string> cmd
typedef struct StrList {
    Str *items;
    size_t len;
    size_t cap;
} StrList;

static void strlist_init(StrList *list) {
    list->items = NULL;
    list->len = 0;
    list->cap = 0;
}

static void strlist_push(StrList *list, Str s) {
    if (list->len == list->cap) {
        list->cap = list->cap ? list->cap * 2 : 8;
        list->items = (Str *)realloc(list->items, list->cap * sizeof(Str));
        if (!list->items) {
            die("realloc error");
        }
    }
    list->items[list->len++] = s;
}

static void strlist_free(StrList *list) {
    free(list->items);
    list->items = NULL;
    list->len = 0;
    list->cap = 0;
}

static bool str_eq(const Str *s, const char *lit) {
    size_t lit_len = strlen(lit);
    return s->len == lit_len && memcmp(s->data, lit, lit_len) == 0;
}

// -------------------------------------------------------------------------------------
// parsing helpers (equivalent of read_u32/read_str/parse_req)
// -------------------------------------------------------------------------------------

static bool read_u32(const uint8_t **cur, const uint8_t *end, uint32_t *out) {
    if (*cur + 4 > end) {
        return false;
    }
    memcpy(out, *cur, 4);
    *cur += 4;
    return true;
}

static bool read_str(const uint8_t **cur, const uint8_t *end, size_t n, Str *out) {
    if (*cur + n > end) {
        return false;
    }
    out->data = *cur;   // no copy: points into the caller's buffer
    out->len = n;
    *cur += n;
    return true;
}

// +------+-----+------+-----+------+-----+-----+------+
// | nstr | len | str1 | len | str2 | ... | len | strn |
// +------+-----+------+-----+------+-----+-----+------+
static int32_t parse_req(const uint8_t *data, size_t size, StrList *out) {
    const uint8_t *end = data + size;
    uint32_t nstr = 0;
    if (!read_u32(&data, end, &nstr)) {
        return -1;
    }
    if (nstr > k_max_args) {
        return -1;  // safety limit
    }

    while (out->len < nstr) {
        uint32_t len = 0;
        if (!read_u32(&data, end, &len)) {
            return -1;
        }
        Str s;
        if (!read_str(&data, end, len, &s)) {
            return -1;
        }
        strlist_push(out, s);
    }
    if (data != end) {
        return -1;  // trailing garbage
    }
    return 0;
}

// -------------------------------------------------------------------------------------
// RESPONSE ----------------------------------------------------------------------------

// Response::status
enum {
    RES_OK = 0,
    RES_ERR = 1,    // error
    RES_NX = 2,     // key not found
};

// +--------+---------+
// | status | data... |
// +--------+---------+
typedef struct Response {
    uint32_t status;
    uint8_t *data;      // owned, malloc'd; NULL if empty
    size_t data_len;
} Response;

// placeholder; implemented later with a real hashtable
typedef struct {
    uint8_t *key;
    size_t key_len;
    uint8_t *val;
    size_t val_len;
} KVPair;

static KVPair *g_data = NULL;
static size_t g_data_len = 0;
static size_t g_data_cap = 0;

static ssize_t g_data_find(const Str *key) {
    for (size_t i = 0; i < g_data_len; i++) {
        if (g_data[i].key_len == key->len &&
            memcmp(g_data[i].key, key->data, key->len) == 0) {
            return (ssize_t)i;
        }
    }
    return -1;
}

static void g_data_set(const Str *key, const Str *val) {
    ssize_t idx = g_data_find(key);
    if (idx >= 0) {
        free(g_data[idx].val);
        g_data[idx].val = (uint8_t *)malloc(val->len);
        memcpy(g_data[idx].val, val->data, val->len);
        g_data[idx].val_len = val->len;
        return;
    }
    if (g_data_len == g_data_cap) {
        g_data_cap = g_data_cap ? g_data_cap * 2 : 16;
        g_data = (KVPair *)realloc(g_data, g_data_cap * sizeof(KVPair));
        if (!g_data) {
            die("realloc error");
        }
    }
    KVPair *kv = &g_data[g_data_len++];
    kv->key = (uint8_t *)malloc(key->len);
    memcpy(kv->key, key->data, key->len);
    kv->key_len = key->len;
    kv->val = (uint8_t *)malloc(val->len);
    memcpy(kv->val, val->data, val->len);
    kv->val_len = val->len;
}

static void g_data_del(const Str *key) {
    ssize_t idx = g_data_find(key);
    if (idx < 0) {
        return;
    }
    free(g_data[idx].key);
    free(g_data[idx].val);
    g_data[idx] = g_data[g_data_len - 1];  // swap-remove, O(1)
    g_data_len--;
}

static void do_request(const StrList *cmd, Response *out) {
    if (cmd->len == 2 && str_eq(&cmd->items[0], "get")) {
        ssize_t idx = g_data_find(&cmd->items[1]);
        if (idx < 0) {
            out->status = RES_NX;   // not found
            return;
        }
        out->data = (uint8_t *)malloc(g_data[idx].val_len);
        memcpy(out->data, g_data[idx].val, g_data[idx].val_len);
        out->data_len = g_data[idx].val_len;
    } else if (cmd->len == 3 && str_eq(&cmd->items[0], "set")) {
        g_data_set(&cmd->items[1], &cmd->items[2]);
    } else if (cmd->len == 2 && str_eq(&cmd->items[0], "del")) {
        g_data_del(&cmd->items[1]);
    } else {
        out->status = RES_ERR;      // unrecognized command
    }
}

static void make_response(const Response *resp, Buffer *out) {
    uint32_t resp_len = 4 + (uint32_t)resp->data_len;
    buf_append(out, (const uint8_t *)&resp_len, 4);
    buf_append(out, (const uint8_t *)&resp->status, 4);
    if (resp->data_len > 0) {
        buf_append(out, resp->data, resp->data_len);
    }
}

// process 1 request if there is enough data
static bool try_one_request(Conn *conn) {
    // try to parse the protocol: message header
    if (buf_len(&conn->incoming) < 4) {
        return false;   // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data_begin, 4);
    if (len > k_max_msg) {
        msg("too long");
        conn->want_close = true;
        return false;   // want close
    }
    // message body
    if (4 + len > buf_len(&conn->incoming)) {
        return false;   // want read
    }
    const uint8_t *request = &conn->incoming.data_begin[4];

    // got one request, do some application logic
    StrList cmd;
    strlist_init(&cmd);
    if (parse_req(request, len, &cmd) < 0) {
        msg("bad request");
        conn->want_close = true;
        strlist_free(&cmd);
        return false;   // want close
    }
    Response resp = {0};
    do_request(&cmd, &resp);
    make_response(&resp, &conn->outgoing);
    free(resp.data);
    strlist_free(&cmd);

    // application logic done! remove the request message.
    buf_consume(&conn->incoming, 4 + len);
    // Q: Why not just empty the buffer? See the explanation of "pipelining".
    return true;        // success
}

// -------------------------------------------------------------------------------------
// HANDLERS ----------------------------------------------------------------------------

// application callback when the socket is writable
static void handle_write(Conn *conn) {
    assert(buf_len(&conn->outgoing) > 0);
    ssize_t rv = write(conn->fd, conn->outgoing.data_begin, buf_len(&conn->outgoing));
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    if (rv < 0) {
        msg_errno("write() error");
        conn->want_close = true;    // error handling
        return;
    }

    // remove written data from `outgoing`
    buf_consume(&conn->outgoing, (size_t)rv);

    // update the readiness intention
    if (buf_len(&conn->outgoing) == 0) {   // all data written
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
}

// application callback when the socket is readable
static void handle_read(Conn *conn) {
    // read some data
    uint8_t buf[64 * 1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    // handle IO error
    if (rv < 0) {
        msg_errno("read() error");
        conn->want_close = true;
        return; // want close
    }
    // handle EOF
    if (rv == 0) {
        if (buf_len(&conn->incoming) == 0) {
            msg("client closed");
        } else {
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return; // want close
    }
    // got some new data
    buf_append(&conn->incoming, buf, (size_t)rv);

    // parse requests and generate responses
    while (try_one_request(conn)) {}
    // Q: Why calling this in a loop? See the explanation of "pipelining".

    // update the readiness intention
    if (buf_len(&conn->outgoing) > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;
        // The socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the next iteration.
        return handle_write(conn);
    }   // else: want read
}

// -------------------------------------------------------------------------------------
// MAIN --------------------------------------------------------------------------------

int main(int argc, char *argv[]) {
    (void)argc;
    (void)argv;

    // the listening socket
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) {
        die("socket()");
    }
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr = {0};
    addr.sin_family = AF_INET;
    addr.sin_port = ntohs(PORT);
    addr.sin_addr.s_addr = ntohl(0);    // wildcard address 0.0.0.0
    int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
    if (rv) {
        die("bind()");
    }

    // set the listen fd to nonblocking mode
    fd_set_nb(fd);

    // listen
    rv = listen(fd, BACKLOG);
    if (rv) {
        die("listen()");
    }

    // a map of all client connections, keyed by fd
    Conn **fd2conn = NULL;
    size_t fd2conn_size = 0;
    // the event loop
    struct pollfd *poll_args = NULL;
    size_t poll_args_cap = 0;
    while (true) {
        // prepare the arguments of the poll()
        size_t nfds = 0;
        // put the listening sockets in the first position
        if (poll_args_cap < 1) {
            poll_args_cap = fd2conn_size + 1;
            poll_args = (struct pollfd *)realloc(poll_args, poll_args_cap * sizeof(struct pollfd));
        }
        struct pollfd pfd = {fd, POLLIN, 0};
        poll_args[nfds++] = pfd;
        // the rest are connection sockets
        for (size_t i = 0; i < fd2conn_size; i++) {
            Conn *conn = fd2conn[i];
            if (!conn) {
                continue;
            }
            if (nfds >= poll_args_cap) {
                poll_args_cap *= 2;
                poll_args = (struct pollfd *)realloc(poll_args, poll_args_cap * sizeof(struct pollfd));
            }
            // always poll() for error
            struct pollfd cpfd = {conn->fd, POLLERR, 0};
            // poll() flags from the application's intent
            if (conn->want_read) {
                cpfd.events |= POLLIN;
            }
            if (conn->want_write) {
                cpfd.events |= POLLOUT;
            }
            poll_args[nfds++] = cpfd;
        }

        // wait for readiness
        int rv = poll(poll_args, (nfds_t)nfds, -1);
        if (rv < 0 && errno == EINTR) {
            continue;   // not an error
        }
        if (rv < 0) {
            die("poll");
        }

        // handle the listening socket
        if (poll_args[0].revents) {
            Conn *conn = handle_accept(fd);
            if (conn) {
                // put it into the map
                if (fd2conn_size <= (size_t)conn->fd) {
                    size_t new_size = (size_t)conn->fd + 1;
                    fd2conn = (Conn **)realloc(fd2conn, new_size * sizeof(Conn *));
                    for (size_t i = fd2conn_size; i < new_size; i++) {
                        fd2conn[i] = NULL;
                    }
                    fd2conn_size = new_size;
                }
                assert(!fd2conn[conn->fd]);
                fd2conn[conn->fd] = conn;
            }
        }

        // handle connection sockets
        for (size_t i = 1; i < nfds; ++i) { // note: skip the 1st
            uint32_t ready = poll_args[i].revents;
            if (ready == 0) {
                continue;
            }

            Conn *conn = fd2conn[poll_args[i].fd];
            if (ready & POLLIN) {
                assert(conn->want_read);
                handle_read(conn);  // application logic
            }
            if (ready & POLLOUT) {
                assert(conn->want_write);
                handle_write(conn); // application logic
            }

            // close the socket from socket error or application logic
            if ((ready & POLLERR) || conn->want_close) {
                (void)close(conn->fd);
                fd2conn[conn->fd] = NULL;
                buf_free(&conn->incoming);
                buf_free(&conn->outgoing);
                free(conn);
            }
        }   // for each connection sockets
    }   // the event loop

    free(poll_args);
    free(fd2conn);
    return 0;

}
