// stdlib
#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
// system
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>


#define PORT 3490
#define BACKLOG 10
// #define k_max_msg 4096
const size_t k_max_msg = 32 << 20;

// -------------------------------------------------------------------------------------
// HELPERS -----------------------------------------------------------------------------

static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
    fprintf(stderr, "[%d] %s\n", errno, msg);
    abort();
}

static void fd_set_nb(int fd) {
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    (void)fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error");
    }
}

// -------------------------------------------------------------------------------------
// VECTOR ------------------------------------------------------------------------------

// a growable byte buffer, replaces std::vector<uint8_t>
typedef struct {
    uint8_t *data;
    size_t len;
    size_t cap;
} Buffer;

static void buf_init(Buffer *buf) {
    buf->data = NULL;
    buf->len = 0;
    buf->cap = 0;
}

static void buf_free(Buffer *buf) {
    free(buf->data);
    buf->data = NULL;
    buf->len = 0;
    buf->cap = 0;
}

// append to the back
static void buf_append(Buffer *buf, const uint8_t *data, size_t len) {
    if (buf->len + len > buf->cap) {
        size_t new_cap = buf->cap ? buf->cap * 2 : 64;
        while (new_cap < buf->len + len) {
            new_cap *= 2;
        }
        uint8_t *new_data = (uint8_t *)realloc(buf->data, new_cap);
        if (!new_data) {
            die("realloc error");
        }
        buf->data = new_data;
        buf->cap = new_cap;
    }
    memcpy(buf->data + buf->len, data, len);
    buf->len += len;
}

// remove from the front
static void buf_consume(Buffer *buf, size_t n) {
    assert(n <= buf->len);
    memmove(buf->data, buf->data + n, buf->len - n);
    buf->len -= n;
}

// -------------------------------------------------------------------------------------
// CONN --------------------------------------------------------------------------------

typedef struct Conn {
    int fd;
    // application's intention, for the event loop
    bool want_read;
    bool want_write;
    bool want_close;
    // buffered input and output
    Buffer incoming;  // data to be parsed by the application
    Buffer outgoing;  // responses generated by the application
} Conn;

// application callback when the listening socket is ready
static Conn *handle_accept(int fd) {
    // accept
    struct sockaddr_in client_addr = {0};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0) {
        msg_errno("accept() error");
        return NULL;
    }
    uint32_t ip = client_addr.sin_addr.s_addr;
    fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",
        ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
        ntohs(client_addr.sin_port)
    );

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    // create a `struct Conn`
    Conn *conn = (Conn *)malloc(sizeof(Conn));
    memset(conn, 0, sizeof(Conn));
    conn->fd = connfd;
    conn->want_read = true;
    buf_init(&conn->incoming);
    buf_init(&conn->outgoing);
    return conn;
}

// process 1 request if there is enough data
static bool try_one_request(Conn *conn) {
    // try to parse the protocol: message header
    if (conn->incoming.len < 4) {
        return false;   // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data, 4);
    if (len > k_max_msg) {
        msg("too long");
        conn->want_close = true;
        return false;   // want close
    }
    // message body
    if (4 + len > conn->incoming.len) {
        return false;   // want read
    }
    const uint8_t *request = &conn->incoming.data[4];

    // got one request, do some application logic
    printf("client says: len:%d data:%.*s\n",
        len, len < 100 ? len : 100, request);

    // generate the response (echo)
    buf_append(&conn->outgoing, (const uint8_t *)&len, 4);
    buf_append(&conn->outgoing, request, len);

    // application logic done! remove the request message.
    buf_consume(&conn->incoming, 4 + len);
    // Q: Why not just empty the buffer? See the explanation of "pipelining".
    return true;        // success
}

// -------------------------------------------------------------------------------------
// HANDLERS ----------------------------------------------------------------------------

// application callback when the socket is writable
static void handle_write(Conn *conn) {
    assert(conn->outgoing.len > 0);
    ssize_t rv = write(conn->fd, conn->outgoing.data, conn->outgoing.len);
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    if (rv < 0) {
        msg_errno("write() error");
        conn->want_close = true;    // error handling
        return;
    }

    // remove written data from `outgoing`
    buf_consume(&conn->outgoing, (size_t)rv);

    // update the readiness intention
    if (conn->outgoing.len == 0) {   // all data written
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
}

// application callback when the socket is readable
static void handle_read(Conn *conn) {
    // read some data
    uint8_t buf[64 * 1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    // handle IO error
    if (rv < 0) {
        msg_errno("read() error");
        conn->want_close = true;
        return; // want close
    }
    // handle EOF
    if (rv == 0) {
        if (conn->incoming.len == 0) {
            msg("client closed");
        } else {
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return; // want close
    }
    // got some new data
    buf_append(&conn->incoming, buf, (size_t)rv);

    // parse requests and generate responses
    while (try_one_request(conn)) {}
    // Q: Why calling this in a loop? See the explanation of "pipelining".

    // update the readiness intention
    if (conn->outgoing.len > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;
        // The socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the next iteration.
        return handle_write(conn);
    }   // else: want read
}

// -------------------------------------------------------------------------------------
// MAIN --------------------------------------------------------------------------------

int main(int argc, char *argv[]) {
    (void)argc;
    (void)argv;

    // the listening socket
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) {
        die("socket()");
    }
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr = {0};
    addr.sin_family = AF_INET;
    addr.sin_port = ntohs(PORT);
    addr.sin_addr.s_addr = ntohl(0);    // wildcard address 0.0.0.0
    int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
    if (rv) {
        die("bind()");
    }

    // set the listen fd to nonblocking mode
    fd_set_nb(fd);

    // listen
    rv = listen(fd, BACKLOG);
    if (rv) {
        die("listen()");
    }

    // a map of all client connections, keyed by fd
    Conn **fd2conn = NULL;
    size_t fd2conn_size = 0;
    // the event loop
    struct pollfd *poll_args = NULL;
    size_t poll_args_cap = 0;
    while (true) {
        // prepare the arguments of the poll()
        size_t nfds = 0;
        // put the listening sockets in the first position
        if (poll_args_cap < 1) {
            poll_args_cap = fd2conn_size + 1;
            poll_args = (struct pollfd *)realloc(poll_args, poll_args_cap * sizeof(struct pollfd));
        }
        struct pollfd pfd = {fd, POLLIN, 0};
        poll_args[nfds++] = pfd;
        // the rest are connection sockets
        for (size_t i = 0; i < fd2conn_size; i++) {
            Conn *conn = fd2conn[i];
            if (!conn) {
                continue;
            }
            if (nfds >= poll_args_cap) {
                poll_args_cap *= 2;
                poll_args = (struct pollfd *)realloc(poll_args, poll_args_cap * sizeof(struct pollfd));
            }
            // always poll() for error
            struct pollfd cpfd = {conn->fd, POLLERR, 0};
            // poll() flags from the application's intent
            if (conn->want_read) {
                cpfd.events |= POLLIN;
            }
            if (conn->want_write) {
                cpfd.events |= POLLOUT;
            }
            poll_args[nfds++] = cpfd;
        }

        // wait for readiness
        int rv = poll(poll_args, (nfds_t)nfds, -1);
        if (rv < 0 && errno == EINTR) {
            continue;   // not an error
        }
        if (rv < 0) {
            die("poll");
        }

        // handle the listening socket
        if (poll_args[0].revents) {
            Conn *conn = handle_accept(fd);
            if (conn) {
                // put it into the map
                if (fd2conn_size <= (size_t)conn->fd) {
                    size_t new_size = (size_t)conn->fd + 1;
                    fd2conn = (Conn **)realloc(fd2conn, new_size * sizeof(Conn *));
                    for (size_t i = fd2conn_size; i < new_size; i++) {
                        fd2conn[i] = NULL;
                    }
                    fd2conn_size = new_size;
                }
                assert(!fd2conn[conn->fd]);
                fd2conn[conn->fd] = conn;
            }
        }

        // handle connection sockets
        for (size_t i = 1; i < nfds; ++i) { // note: skip the 1st
            uint32_t ready = poll_args[i].revents;
            if (ready == 0) {
                continue;
            }

            Conn *conn = fd2conn[poll_args[i].fd];
            if (ready & POLLIN) {
                assert(conn->want_read);
                handle_read(conn);  // application logic
            }
            if (ready & POLLOUT) {
                assert(conn->want_write);
                handle_write(conn); // application logic
            }

            // close the socket from socket error or application logic
            if ((ready & POLLERR) || conn->want_close) {
                (void)close(conn->fd);
                fd2conn[conn->fd] = NULL;
                buf_free(&conn->incoming);
                buf_free(&conn->outgoing);
                free(conn);
            }
        }   // for each connection sockets
    }   // the event loop

    free(poll_args);
    free(fd2conn);
    return 0;

}
